name: google_maps_angular_dart
version: 0.0.1
description: Angular application with Google Maps integration
environment:
  sdk: '>=2.5.0 <3.0.0'
dependencies:
  angular: ^6.0.0-alpha+1
  angular_components: 0.14.0-alpha+1
  angular_forms: ^2.1.0
  google_maps: ^3.0.0
dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.3.0
  build_test: ^0.10.0
  build_web_compilers: ^2.4.0
  test: ^1.6.0
