
name: JS style

on:
  push:
    branches: [master, development, andrewDev, priyaDevelopment, emmaDevelopment]
  pull_request:
    branches: [master, development, andrewDev, priyaDevelopment, emmaDevelopment]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.3
        # GITHUB_TOKEN in forked repositories is read-only
        # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
