
name: JS style

on:
  push:
    branches: [master, development, andrewDev, priyaDevelopment, emmaDevelopment]
  pull_request:
    branches: [master, development, andrewDev, priyaDevelopment, emmaDevelopment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: initialization npm
      run: npm init
    - name: Install ESlint
      run: npm install eslint --save-dev
    - name: Run ESlint
      run: eslint ./where-to-travel/src/main/webapp --ext .js
